# Generated by Django 2.1.7 on 2019-05-23 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='creditscore11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=500)),
                ('potential_defaulter', models.BooleanField(default=True)),
                ('footprint_updated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.IntegerField()),
                ('pay_0', models.IntegerField(choices=[(2, 'Paid after 2 month'), (-1, 'Paid before time'), (4, 'Paid after 4 month'), (5, 'Paid after 5 month'), (7, 'Paid after 7 month'), (6, 'Paid after 6 month'), (0, 'Paid on time'), (1, 'Paid after 1 month'), (3, 'Paid after 3 month'), (8, 'Paid after 8 month')], default=-1, help_text='1st Loan status')),
                ('pay_1', models.IntegerField(choices=[(2, 'Paid after 2 month'), (-1, 'Paid before time'), (4, 'Paid after 4 month'), (5, 'Paid after 5 month'), (7, 'Paid after 7 month'), (6, 'Paid after 6 month'), (0, 'Paid on time'), (1, 'Paid after 1 month'), (3, 'Paid after 3 month'), (8, 'Paid after 8 month')], default=-1, help_text='2nd Loan status')),
                ('pay_2', models.IntegerField(choices=[(2, 'Paid after 2 month'), (-1, 'Paid before time'), (4, 'Paid after 4 month'), (5, 'Paid after 5 month'), (7, 'Paid after 7 month'), (6, 'Paid after 6 month'), (0, 'Paid on time'), (1, 'Paid after 1 month'), (3, 'Paid after 3 month'), (8, 'Paid after 8 month')], default=-1, help_text='2nd Loan status')),
                ('pay_3', models.IntegerField(choices=[(2, 'Paid after 2 month'), (-1, 'Paid before time'), (4, 'Paid after 4 month'), (5, 'Paid after 5 month'), (7, 'Paid after 7 month'), (6, 'Paid after 6 month'), (0, 'Paid on time'), (1, 'Paid after 1 month'), (3, 'Paid after 3 month'), (8, 'Paid after 8 month')], default=-1, help_text='2nd Loan status')),
                ('pay_4', models.IntegerField(choices=[(2, 'Paid after 2 month'), (-1, 'Paid before time'), (4, 'Paid after 4 month'), (5, 'Paid after 5 month'), (7, 'Paid after 7 month'), (6, 'Paid after 6 month'), (0, 'Paid on time'), (1, 'Paid after 1 month'), (3, 'Paid after 3 month'), (8, 'Paid after 8 month')], default=-1, help_text='2nd Loan status')),
                ('pay_5', models.IntegerField(choices=[(2, 'Paid after 2 month'), (-1, 'Paid before time'), (4, 'Paid after 4 month'), (5, 'Paid after 5 month'), (7, 'Paid after 7 month'), (6, 'Paid after 6 month'), (0, 'Paid on time'), (1, 'Paid after 1 month'), (3, 'Paid after 3 month'), (8, 'Paid after 8 month')], default=-1, help_text='2nd Loan status')),
                ('bill_amt1', models.IntegerField(default=0, help_text='1st Loan amount')),
                ('bill_amt2', models.IntegerField(default=0)),
                ('bill_amt3', models.IntegerField(default=0)),
                ('bill_amt4', models.IntegerField(default=0)),
                ('bill_amt5', models.IntegerField(default=0)),
                ('bill_amt6', models.IntegerField(default=0)),
                ('pay_amt1', models.IntegerField(default=0)),
                ('pay_amt2', models.IntegerField(default=0)),
                ('pay_amt3', models.IntegerField(default=0)),
                ('pay_amt4', models.IntegerField(default=0)),
                ('pay_amt5', models.IntegerField(default=0)),
                ('pay_amt6', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('is_married', models.BooleanField(default=False)),
                ('No_of_Degrees', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='footprint',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Profile'),
        ),
        migrations.AddField(
            model_name='creditscore11',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Profile'),
        ),
    ]
